version: '3.4'

x-common-variables: &common-variables
  HSELING_RPC_ENDPOINT: http://hse-api-web:80/rpc/
  HSELING_API_ENDPOINT: http://hse-api-web:80/api/
  RESTRICTED_MODE: 0

services:
  hse-api-web:
    build:
      context: .
      dockerfile: hseling-api-e-shvarts/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - type: bind
        source: ./hseling-api-e-shvarts/hseling_api_e_shvarts
        target: /app/hseling_api_e_shvarts
      - type: bind
        source: ./hseling-data-e-shvarts/api
        target: /data
    environment: *common-variables






  hse-web-web:
    build:
      context: .
      dockerfile: hseling-web-e-shvarts/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - hse-api-web
    environment: *common-variables
    volumes:
      - type: bind
        source: ./hseling-web-e-shvarts/hseling_web_e_shvarts
        target: /app/hseling_web_e_shvarts
      - type: bind
        source: ./hseling-web-e-shvarts/hseling_web_e_shvarts/static
        target: /app/static
      - type: bind
        source: ./hseling-data-e-shvarts/web
        target: /data
